### ISSUE TITLE
maps.openrouteservice.org "no internet connection" Error

### ISSUE THREAD

**Issue by heinerolli** [GIScience/openrouteservice-app#235]
When I use multiple features, such as "avoid hills" and a low number (i.e. 3%) for "steepness", I get the error "no internet connection" regardless of the device (PC / Smartphone) and browser type I use. So this should be a bug.
I guess this goes along my other reported bug (missing elevation plot) in the cathegory "Please priotize the development of a more responsive Web-Skin"
![image](https://user-images.githubusercontent.com/37367314/41811402-244d5a96-770f-11e8-8ebe-b7d3aa8fca8b.png)

**Comment by aoles** [comment]
When no route can be found (e.g. because of some restrictions enabled) an error message `Please check your internet connection` pops up even though the underlying problem is the backend not being able to find the route.

Consider displaying the actual error message from the api response instead of the spurious network error.
