### ISSUE TITLE
Why is Pye related to Oldenburg instead of Osnabrück?

### ISSUE THREAD

**Issue by SebAlbert** [GIScience/openrouteservice-app#291]
Last year I noticed a wrong connection of geo-things in #244 and was pointed to Pelias and from there to their data provider. However, this time their data provider seems to be fine, but still maps.openrouteservice.org seems to be wrong.

It's about a place called "Pye", which is part of Osnabrück, Germany. Correctly identified by a search on spelunker.whosonfirst.org: https://spelunker.whosonfirst.org/id/1393620319/
Everything there points to Osnabrück, nothing hinting at Oldenburg, as far as I can see.

However, searching for Pye on maps.openrouteservice.org yields (next to places in other parts of the world) a Pye, allegedly coming from "source: whosonfirst" (according to the mouseover), that is said to be related to Oldenburg in the subtitle, although the geo-coordinates are correct anyway. It seems only this subtitle is wrong. I would really like to understand what's going wrong there, but I can't. I even don't know where to report it this time, so I'm starting here again.

**Comment by TimMcCauley** [comment]
@SebAlbert thank you - we will look into this.

@TheGreatRefrigerator do you have time to check what is going on here? If it isn't a client issue we can forward to our friend @nilsnolde  ;-)

**Comment by TheGreatRefrigerator** [comment]
the node relating to Oldenburg was deprecated on whosonfirst at 20.05.2019.
https://spelunker.whosonfirst.org/id/1210038279/
maybe our database is not up to date?
maps.openrouteservice still gets the one related to Oldenburg back from the api call.
Maybe @nilsnolde can take a look? 👀

**Comment by nilsnolde** [comment]
As far as I can see, nothing ever refers to Oldenburg in WOF, neither the deprecated 1210038279 nor the superseding 1393620319. Where do you see Oldenburg in 1210038279 @TheGreatRefrigerator?

Although that would've made sense, since our data was last updated around mid April before tonight. But now I just finished a global import on the new ES 5 setup and I still get the same result:

https://api.openrouteservice.org/geocode/search?text=Pye

In the 3rd entry, there's again a `county` referring to Oldenburg with an ID of 102063901, which in turn references [Osnabrück](https://spelunker.whosonfirst.org/id/102063901/) correctly in WOF, but somehow Pelias gets the wrong name. Maybe @missinglink can shed some light on this.

**Comment by nilsnolde** [comment]
referenced in pelias repo.

**Comment by TheGreatRefrigerator** [comment]
Hmm but the ID of the superseeded match with the ID of the geocoding result which referst to oldenburg.
So in the response of https://api.openrouteservice.org/geocode/search?text=Pye you should also have the WOF ID of 1210038279
![grafik](https://user-images.githubusercontent.com/23240110/63301001-d04e6080-c2d9-11e9-99e9-627f45b138bf.png)
I am not sure where the county information comes from then

**Comment by nilsnolde** [comment]
Oh right, I didn't see that the `gid` references the deprecated ID. But ALL IDs, regardless where they show up, reference WOF and all those WOF entries correctly identify Osnabrück. So, my guess is that Pelias is getting a little confused. All these entries come from `geonames`, shouldn't have anything to do with it though...

**Comment by pathmapper** [comment]
I think this issue is related to WOF 102063901:
https://spelunker.whosonfirst.org/id/102063901/

There is some information regarding Oldenburg which doesn't belong there, possibly related to a wrong Statoids reference.

![image](https://user-images.githubusercontent.com/20856381/63326026-aa51ac00-c32b-11e9-93c4-7aea8471357f.png)

![image](https://user-images.githubusercontent.com/20856381/63326631-ee917c00-c32c-11e9-8398-8c9aad2afea1.png)


![image](https://user-images.githubusercontent.com/20856381/63326166-f00e7480-c32b-11e9-8b4b-b88fc138bed3.png)
![image](https://user-images.githubusercontent.com/20856381/63326951-8d1ddd00-c32d-11e9-89e2-3eaad904f78d.png)

**Comment by nilsnolde** [comment]
Ah nice thx @pathmapper! Weird, thought I searched for Oldernburg references on all those spelunker ID pages.. Then it's a data issue, that's good! Can you also update it? I have no idea how to about updating WOF records.

**Comment by pathmapper** [comment]
> Can you also update it?

@nilsnolde yep, working on it in https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/13

**Comment by TheGreatRefrigerator** [comment]
I consider this closed then

**Comment by pathmapper** [comment]
This is fixed in WOF: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/17

**Comment by SebAlbert** [comment]
Thanks for all your investigations!

Is this waiting for a next bulk data load? It's still displaying wrong in some places:

![image](https://user-images.githubusercontent.com/2102858/70913567-8a4ea280-2016-11ea-89bb-4994ba143d7d.png)
