### ISSUE TITLE
Remove fastest, default to recommended

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice-app#315]
Recommended and Fastest are basically the same.
Therefore Fastest should be removed.

**Comment by marq24** [comment]
just for your consideration...

Fastest: [give you a route]
https://maps.openrouteservice.org/directions?n1=46.28086&n2=4.805163&n3=7&a=48.858705,2.342865,43.70313,7.26608&b=1a&c=0&k1=en-US&k2=km

while Recommended [gives you a server error]
https://maps.openrouteservice.org/directions?n1=46.28086&n2=4.805163&n3=7&a=48.858705,2.342865,43.70313,7.26608&b=1a&c=2&k1=en-US&k2=km

so they are not the "same" right now - but i might have [misunderstood] something fundamental

**Comment by TheGreatRefrigerator** [comment]
We just had a whole meeting on this. Will provide an explanation soon.

**Comment by aoles** [comment]
> while Recommended [gives you a server error]

This happens because the current default routing algorithm which is CH does not support `recommended` weighting, just `fastest`. In the case of recommended all routes are computed with the dynamic ALT algorithm which has a distance limit of 300km. You will get the same error for fastest as well as soon as you enable any of the filters, such as `avoid=ferries`.

We hope to address these shortcomings by switching to CALT which has the performance of CH yet allows the flexibility of ALT.
